service: dialogflow-data-issue

custom:
  allowedHeaders:
    - x-user
    - Accept
    - Content-Type
    - Content-Length
    - Authorization

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  stage: test
  memorySize: 128
  timeout: 5
  endpointType: regional

functions:
  main-request:
    handler: index.handler
    description: post /request
    events:
      - http:
          path: request
          method: post
          integration: lambda
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}
          request:
            template:
              application/json: >
                {
                "method": "$context.httpMethod",
                "body" : $input.json('$'),
                "headers": {
                  #foreach($param in $input.params().header.keySet())
                  "$param": "$util.escapeJavaScript($input.params().header.get($param))" #if($foreach.hasNext),#end
                  #end
                },
                "queryParams": {
                  #foreach($param in $input.params().querystring.keySet())
                  "$param": "$util.escapeJavaScript($input.params().querystring.get($param))" #if($foreach.hasNext),#end
                  #end
                },
                "pathParams": {
                  #foreach($param in $input.params().path.keySet())
                  "$param": "$util.escapeJavaScript($input.params().path.get($param))" #if($foreach.hasNext),#end
                  #end
                }
                }
